# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Run after sonarcloud.yml-job has finished successfuly
    needs: sonarcloud
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.17.0
          check-latest: true

      - name: Print versions
        run: |
          node -v
          npm -v

      - name: NPM Scripts
        run: |
          npm ci
          npm run build

      - name: Archive build artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: SCP Files
        if: ${{ success() }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: 'dist/*'
          target: ${{ secrets.TARGET }}
          rm: true
          strip_components: 1
