name: Deploy

on:
  workflow_run:
    workflows: ['Sonar']
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 14.17.0
          check-latest: true

      - name: Print versions
        run: |
          node -v
          npm -v

      - name: NPM Scripts
        run: |
          npm ci
          npm run build

      - name: Archive build artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: SCP Files
        if: ${{ success() }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: 'dist/*'
          target: ${{ secrets.TARGET }}
          # rm: true
          strip_components: 1
